---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-1
spec:
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs.csi.k8s.io
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/loki-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
spec:
  storageClassName: nfs.csi.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
