---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-1
spec:
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs.csi.k8s.io
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  storageClassName: nfs.csi.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-grafana-pv-1
spec:
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs.csi.k8s.io
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus-grafana-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-grafana-pvc
spec:
  storageClassName: nfs.csi.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
