---
image:
  repository: zodinettech/wash24-car-detector-api
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred-dockerhub
services:
  - name: http
    port: 80
    targetPort: 8080

livenessProbe:
  httpGet:
    path: /
    port: 8080
readinessProbe:
  httpGet:
    path: /
    port: 8080
startupProbe:
  httpGet:
    path: /
    port: 8080
  failureThreshold: 20
  periodSeconds: 10
podAnnotations: