# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  build_time = Time.now.strftime('%Y%m%d')

  lane :release do 
    build_ios_app(
      scheme: "wash-prod", 
      workspace: "mobile.xcworkspace", 
      output_directory: "./build", 
      output_name: "jetx.ipa",
      clean: true, 
      configuration: "Release",
      include_bitcode: false,
      xcargs: "-UseModernBuildSystem=YES",
      export_team_id: "HP2NNAZ9NG",
      export_method: "development",
      export_xcargs: "-allowProvisioningUpdates",
    )
  end
  lane :dev do 
    build_ios_app(
      scheme: "wash-dev", 
      workspace: "mobile.xcworkspace", 
      output_directory: "./build", 
      output_name: "jetx-dev.ipa",
      clean: true, 
      configuration: "Release",
      include_bitcode: false,
      xcargs: "-UseModernBuildSystem=YES",
      export_team_id: "8ZTPMPG9Y5",
      export_method: "development",
      export_xcargs: "-allowProvisioningUpdates",
    )
  end

end

