name: WASH24 API - DEV
run-name: |
  ${{ format('Build and publish {0}/{1}:{2} by @{3}',
      github.event.inputs.registry,
      github.event.inputs.service,
      github.run_number,
      github.actor) }}


on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker provider'
        required: true
        default: 'zodinettech'
      service:
        description: 'Service name'
        required: true
        default: 'wash24-api'
  push:
    branches:
      - dev

env:
  IMAGE_NAME: ${{ inputs.service || 'wash24-api' }}
  REGISTRY: ${{ inputs.registry || 'zodinettech'}}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_tag.outputs.version }}
      docker_tags: ${{ steps.get_tag.outputs.docker_tags }}
      docker_encoded_tags: ${{ steps.get_tag.outputs.docker_encoded_tags }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get tag name
        id: get_tag
        run: |
          VERSION="${{ github.run_number }}"
          DOCKER_TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "docker_tags=${DOCKER_TAGS}" >> $GITHUB_OUTPUT
          docker_encoded_tags=$(echo -n "$DOCKER_TAGS" | base64)
          echo "docker_encoded_tags=${docker_encoded_tags}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.get_tag.outputs.docker_tags }}
          build-args: |
            SWAGGER_VERSION=${{ steps.get_tag.outputs.version }}
