name: Kiosk Web - Build
run-name: |
  ${{ format('Build Tags {0} by @{1}',
      github.ref_name,
      github.actor) }}

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: wash24-kiosk-web
  REGISTRY: zodinettech

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_tag.outputs.version }}
      docker_tags: ${{ steps.get_tag.outputs.docker_tags }}

    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get tag name
        id: get_tag
        run: |
          if [[ $GITHUB_REF = refs/tags/* ]]
          then
            VERSION="${GITHUB_REF/refs\/tags\//}"
            DOCKER_TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "docker_tags=${DOCKER_TAGS}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.get_tag.outputs.docker_tags }}
