name: Build Helmfile Args
inputs:
  helmfile_version:
    default: "v0.150.0"
outputs:
  helmfile_args:
    description: "args for helmfile"
    value: ${{ steps.helmfile_selectors.outputs.helmfile_args }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: '**/actions/build_helmfile_args/requirements.txt'

    - shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.2.0
      with:
        helmfile-version: "${{ inputs.helmfile_version }}"

    - name: get branch to compare
      id: compare_branch
      shell: bash
      run: |
        if [[ "${{ github.event.repository.default_branch }}" == "${{ github.ref_name }}" ]]; then
          echo 'compare_branch=HEAD~1' >> $GITHUB_OUTPUT
        else
          echo 'compare_branch=origin/${{ github.event.repository.default_branch }}' >> $GITHUB_OUTPUT
        fi

    - name: Generate service
      shell: bash
      env:
        HELMFILE_GOCCY_GOYAML: true
      id: helmfile_selectors
      run: |
        helmfile repos
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        HELMFILE_SELECTORS="$(
          git --no-pager diff --name-only "${{ steps.compare_branch.outputs.compare_branch }}" "${{ github.sha }}" | \
          python3 .github/actions/build_helmfile_args/helmfile_selectors.py | \
          jq -c
        )"

        echo "helmfile_args=$HELMFILE_SELECTORS" >> $GITHUB_OUTPUT
