apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-env" (include "generic.fullname" .) | quote }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
data: 
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{$v | b64enc | quote }}
  {{- end }}
---
{{- if .Values.secretMounts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-files" (include "generic.fullname" .) | quote }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
data:
  {{- range $key, $file := .Values.secretMounts }}
  {{- if $file.isBase64Encoded }}
  {{ $key }}: {{ $file.value }}
  {{- else }}
  {{ $key }}: {{ $file.value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
